server:
  port: 2020
spring:
  application:
    name: api-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      routes:
        - id: patient-route
          uri:
            http://localhost:8080
          predicates:
            - Path=/patient/**
            - Method=POST
        - id: patient-route-1
          uri:
            http://localhost:8081
          predicates:
            - Path=/patient/**
        - id: doctor-route
          uri:
            lb://doctor-service
          predicates:
            - Path=/api/v1/doctor/**
          filters:
            - StripPrefix=2
eureka:
  client:
    register-with-eureka: true # Whether this service should register itself with Eureka
    fetch-registry: true # Whether to fetch the registry information from Eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka # The URL of the Eureka server
    registry-fetch-interval-seconds: 30 # How often (in seconds) the Eureka client fetches the registry from the server.
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}  # A unique instance ID
    lease-renewal-interval-in-seconds: 30 # Frequency of heartbeats to Eureka server (default: 30)
    lease-expiration-duration-in-seconds: 90 # Time in seconds that Eureka waits before removing a service from the registry (default: 90)